apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: spark-app
spec:
 # clusterIP: None
  ports:
  - port: 9042
  type: LoadBalancer
  selector:
    app: cassandra
